apiVersion: v1
kind: Service
metadata:
  name: alb-tastytap
spec:
  type: LoadBalancer
  selector:
    app: tastytap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000