apiVersion: v1
kind: Service
metadata:
  name: alb-tastytap
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-00a99af01df94fb97,subnet-0d649b7c7f29fa3a0"
spec:
  type: LoadBalancer
  selector:
    app: tastytap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000