apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: ZGJfdXNlcm5hbWU=
  SPRING_DATASOURCE_PASSWORD: ZGJfcGFzc3dvcmQ=
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL3Rhc3R5dGFwLmN6ZW9xNmN3a2YwdC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi90YXN0eXRhcD9jcmVhdGVEYXRhYmFzZUlmTm90RXhpc3Q9dHJ1ZSZ6ZXJvRGF0ZVRpbWVCZWhhdmlvcj1jb252ZXJ0VG9OdWxsJnVzZVNTTD1mYWxzZQ==