apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_DATABASE: dGFzdHl0YXA=
  MYSQL_USER: dGFzdHl0YXA=
  MYSQL_ROOT_PASSWORD: bXVkYXIxMjM=
  MYSQL_PASSWORD: bXVkYXIxMjM=